### ISSUE TITLE
Sequence logo error

### ISSUE THREAD

**Issue by ghost** [mgledi/DiffLogo#5]
The following code works for DNA and RNA alphabet and throws an error for ASN alphabet:

Error in alphabet$cols[[letterOrder[i]]] : subscript out of bounds
in function seqLogo()

createPWM = function(strings, alphabet, pseudoCount) {
  alphabetLength <- length(alphabet$chars)
  stringLengths <- nchar(strings[[1]])
  numberOfStrings <- length(strings)

  pwm <- matrix(nrow = alphabetLength, ncol = stringLengths)
  colnames(pwm) <- 1:stringLengths
  rownames(pwm) <- alphabet$chars

  for(charIdx in 1:alphabetLength){
    for(posIdx in 1:stringLengths){
      pwm[charIdx, posIdx] <- (length(which(substr(strings, posIdx, posIdx) == alphabet$chars[[charIdx]])) + pseudoCount) / (numberOfStrings + pseudoCount \* alphabetLength)
    }
  }

  return(pwm);
}

aa <- as.character(c("A", "A"))
ac <- as.character(c("A", "C"))
ag <- as.character(c("A", "G"))

pwmAa <- createPWM(aa, ASN, 1)
pwmAc <- createPWM(ac, ASN, 1)
pwmAg <- createPWM(ag, ASN, 1)

motifs <- list();
motifs[["aa"]] <- pwmAa
motifs[["ac"]] <- pwmAc
motifs[["ag"]] <- pwmAg
diffLogoTable(PWMs = motifs, alphabet = ASN)

**Comment by ghost** [comment]
we might integrate the function createPWM() into the DiffLogo package as many users may need it

**Comment by mgledi** [comment]
please use alphabet$size instead of length(chars).

Also fixed bug with next commit.
