### ISSUE TITLE
Introduce spacing in logos

### ISSUE THREAD

**Issue by ghost** [mgledi/DiffLogo#7]
Introduce small spacing in logos and DiffLogos between neighbouring stacks and perhaps also between characters of a stack to make it more separate by eye
![rplot03](https://cloud.githubusercontent.com/assets/8747961/6228257/bfa1c54c-b6a9-11e4-945d-9a48f1d914b1.png)

**Comment by mgledi** [comment]
The width of a stack is now multiplied with 0.99.
