### ISSUE TITLE
Cluster-tree is wrong

### ISSUE THREAD

**Issue by ghost** [mgledi/DiffLogo#8]
Eubacteria and archaea are most similar, but according to the tree, they are most dissimilar.
![asn_motif_comparison_01](https://cloud.githubusercontent.com/assets/8747961/6245064/cd4ceb8e-b75a-11e4-8bd8-c424041a1c3d.png)

**Comment by ghost** [comment]
![rplot](https://cloud.githubusercontent.com/assets/8747961/6245490/761000fe-b75f-11e4-87a7-ea1295e55405.png)
Here a minimum example:

aaa <- as.character(c("A", c("A", "A")))
aac <- as.character(c("A", c("A", "C")))
agc <- as.character(c("A", c("G", "C")))

pwmAaa <- getPwmFromAlignment(aaa, ASN, 1)
pwmAac <- getPwmFromAlignment(aac, ASN, 1)
pwmAgc <- getPwmFromAlignment(agc, ASN, 1)

motifs <- list();
motifs[["aaa"]] <- pwmAaa
motifs[["aac"]] <- pwmAac
motifs[["agc"]] <- pwmAgc
diffLogoTable(PWMs = motifs, alphabet = ASN)

**Comment by mgledi** [comment]
Bug fixed. HClust interprets NA as max. Replacing NAs with 0 solves this problem.
