### ISSUE TITLE
Outdated functions

### ISSUE THREAD

**Issue by ghost** [mgledi/DiffLogo#9]
Function 'differenceOfICs' in file 'baseDistrs.R' is using non-existing function 'pwm2ic_col'
the same applies for the function 'sumOfAbsICDifferences' in file 'stackHeights.R'

**Comment by HendrikTreutler** [comment]
the same applies for the function 'sumOfAbsICDifferences' in file 'stackHeights.R'

**Comment by mgledi** [comment]
Fixed.
